/* Generated by:  JJTree&ParserGeneratorCC: Do not edit this line. FunctionParserConstants.java */
package com.github.vincentrussell.json.datagenerator.parser;


/**
 * Token literal values and constants.
 * Generated by com.helger.pgcc.output.java.OtherFilesGenJava#start()
 */
public interface FunctionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING_LITERAL = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 10;
  /** RegularExpression Id. */
  int EXPONENT = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int TERM = 15;
  /** RegularExpression Id. */
  int LETTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<DOUBLE_QUOTED_STRING_LITERAL>",
    "<SINGLE_QUOTED_STRING_LITERAL>",
    "<NUMBER>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<TERM>",
    "<LETTER>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
