/* FunctionParserTokenManager.java */
/* Generated by:  JJTree&ParserGeneratorCC: Do not edit this line. FunctionParserTokenManager.java */
package com.github.vincentrussell.json.datagenerator.parser;
import java.util.List;
import java.util.ArrayList;
import com.github.vincentrussell.json.datagenerator.functions.FunctionRegistry;
import com.google.common.base.Charsets;
import java.lang.reflect.InvocationTargetException;
import java.lang.IllegalAccessException;

/** Token Manager. */
@SuppressWarnings ("unused")
public class FunctionParserTokenManager implements FunctionParserConstants {
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case '(':
         return jjStopAtPos(0, 17);
      case ')':
         return jjStopAtPos(0, 19);
      case ',':
         return jjStopAtPos(0, 18);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 83;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0x0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     { jjCheckNAddStates(0, 13); }
                  }
                  else if (curChar == 45)
                  {
                     if (kind > 14)
                        kind = 14;
                     { jjCheckNAddTwoStates(81, 82); }
                  }
                  else if (curChar == 46)
                     { jjCheckNAddTwoStates(36, 41); }
                  else if (curChar == 47)
                     { jjAddStates(14, 15); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(16, 18); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(19, 21); }
                  if ((0x3fe000000000000L & l) != 0x0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     { jjCheckNAddStates(22, 24); }
                  }
                  else if (curChar == 45)
                     { jjCheckNAddStates(25, 34); }
                  else if (curChar == 48)
                  {
                     if (kind > 9)
                        kind = 9;
                     { jjCheckNAdd(31); }
                  }
                  break;
               case 1:
                  if ((0xfffffffbffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 3:
                  if ((0x8400000000L & l) != 0x0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 4:
                  if (curChar == 34 && kind > 7)
                     kind = 7;
                  break;
               case 5:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(35, 38); }
                  break;
               case 6:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 7:
                  if ((0xf000000000000L & l) != 0x0L)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 8:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAdd(6); }
                  break;
               case 9:
                  if (curChar == 39)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 10:
                  if ((0xffffff7fffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 12:
                  if (curChar == 34)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 13:
                  if (curChar == 39 && kind > 8)
                     kind = 8;
                  break;
               case 14:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(39, 42); }
                  break;
               case 15:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 16:
                  if ((0xf000000000000L & l) != 0x0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0xff000000000000L & l) != 0x0L)
                     { jjCheckNAdd(15); }
                  break;
               case 18:
                  if (curChar == 47)
                     { jjAddStates(14, 15); }
                  break;
               case 19:
                  if (curChar == 47)
                     { jjCheckNAddStates(43, 45); }
                  break;
               case 20:
                  if ((0xffffffffffffdbffL & l) != 0x0L)
                     { jjCheckNAddStates(43, 45); }
                  break;
               case 21:
                  if ((0x2400L & l) != 0x0L && kind > 5)
                     kind = 5;
                  break;
               case 22:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 23:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 25:
                  if ((0xfffffbffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 26:
                  if (curChar == 42)
                     { jjAddStates(46, 47); }
                  break;
               case 27:
                  if ((0xffff7fffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(28, 26); }
                  break;
               case 28:
                  if ((0xfffffbffffffffffL & l) != 0x0L)
                     { jjCheckNAddTwoStates(28, 26); }
                  break;
               case 29:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 30:
                  if (curChar != 48)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAdd(31); }
                  break;
               case 32:
                  if ((0x3fe000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(22, 24); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddTwoStates(33, 31); }
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  { jjCheckNAdd(34); }
                  break;
               case 35:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(36, 41); }
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(48, 50); }
                  break;
               case 38:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(39); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddTwoStates(39, 40); }
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddStates(51, 53); }
                  break;
               case 43:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(44); }
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddTwoStates(44, 45); }
                  break;
               case 46:
                  if (curChar == 45)
                     { jjCheckNAddStates(25, 34); }
                  break;
               case 47:
                  if ((0x3fe000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddTwoStates(33, 31); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(54, 56); }
                  break;
               case 50:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(51); }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(51, 40); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(52, 53); }
                  break;
               case 54:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(55); }
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddTwoStates(55, 40); }
                  break;
               case 56:
                  if (curChar == 46)
                     { jjCheckNAdd(36); }
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(57, 58); }
                  break;
               case 58:
                  if (curChar != 46)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(57, 59); }
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(57, 59); }
                  break;
               case 61:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(62); }
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddTwoStates(62, 40); }
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(63, 64); }
                  break;
               case 64:
                  if (curChar != 46)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddStates(60, 62); }
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddStates(60, 62); }
                  break;
               case 67:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(68); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddTwoStates(68, 45); }
                  break;
               case 69:
                  if (curChar == 46)
                     { jjCheckNAdd(41); }
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(70, 71); }
                  break;
               case 72:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(73); }
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 10)
                     kind = 10;
                  { jjCheckNAddTwoStates(73, 45); }
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddStates(63, 65); }
                  break;
               case 76:
                  if ((0x280000000000L & l) != 0x0L)
                     { jjCheckNAdd(77); }
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0x0L)
                     { jjCheckNAddTwoStates(77, 45); }
                  break;
               case 78:
                  if ((0x3fe000000000000L & l) == 0x0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  { jjCheckNAdd(34); }
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0x0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAddStates(0, 13); }
                  break;
               case 80:
                  if (curChar != 45)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAddTwoStates(81, 82); }
                  break;
               case 81:
                  if ((0x3ff200000000000L & l) == 0x0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAdd(81); }
                  break;
               case 82:
                  if ((0x3ff200000000000L & l) == 0x0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  { jjCheckNAdd(82); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAddTwoStates(81, 82); }
                  break;
               case 1:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 2:
                  if (curChar == 92)
                     { jjAddStates(66, 68); }
                  break;
               case 3:
                  if ((0x14404410000000L & l) != 0x0L)
                     { jjCheckNAddStates(19, 21); }
                  break;
               case 10:
                  if ((0xffffffffefffffffL & l) != 0x0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 11:
                  if (curChar == 92)
                     { jjAddStates(69, 71); }
                  break;
               case 12:
                  if ((0x14404410000000L & l) != 0x0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 20:
                  { jjAddStates(43, 45); }
                  break;
               case 25:
                  { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 27:
               case 28:
                  { jjCheckNAddTwoStates(28, 26); }
                  break;
               case 31:
                  if (curChar == 76 && kind > 9)
                     kind = 9;
                  break;
               case 37:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(72, 73); }
                  break;
               case 40:
                  if ((0x5000000050L & l) != 0x0L && kind > 9)
                     kind = 9;
                  break;
               case 42:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(74, 75); }
                  break;
               case 45:
                  if ((0x5000000050L & l) != 0x0L && kind > 10)
                     kind = 10;
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(76, 77); }
                  break;
               case 53:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(78, 79); }
                  break;
               case 60:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(80, 81); }
                  break;
               case 66:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(82, 83); }
                  break;
               case 71:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(84, 85); }
                  break;
               case 75:
                  if ((0x2000000020L & l) != 0x0L)
                     { jjAddStates(86, 87); }
                  break;
               case 81:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  { jjCheckNAdd(81); }
                  break;
               case 82:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  { jjCheckNAdd(82); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(19, 21); }
                  break;
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(16, 18); }
                  break;
               case 20:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(43, 45); }
                  break;
               case 25:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(25, 26); }
                  break;
               case 27:
               case 28:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(28, 26); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      i = jjnewStateCnt;
      jjnewStateCnt = startsAt;
      startsAt = 83 - jjnewStateCnt;
      if (i == startsAt)
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\50", "\54", "\51", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = im == null ? input_stream.getImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   48, 49, 40, 52, 53, 57, 58, 63, 64, 70, 71, 74, 75, 45, 19, 24, 
   10, 11, 13, 1, 2, 4, 33, 31, 34, 47, 48, 52, 56, 57, 63, 69, 
   70, 74, 78, 1, 2, 6, 4, 10, 11, 15, 13, 20, 21, 23, 27, 29, 
   36, 37, 40, 41, 42, 45, 48, 49, 40, 59, 60, 40, 65, 66, 45, 74, 
   75, 45, 3, 5, 7, 12, 14, 16, 38, 39, 43, 44, 50, 51, 54, 55, 
   61, 62, 67, 68, 72, 73, 76, 77, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop:
  for (;;)
  {
   try
   {
      curChar = input_stream.beginToken();
   }
   catch(final Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try {
     input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0x0L)
         curChar = input_stream.beginToken();
   }
   catch (final java.io.IOException e1) {
     continue EOFLoop;
   }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try {
     input_stream.readChar();
     input_stream.backup(1);
   }
   catch (final java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.getImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.getImage();
   }
   throw new TokenMgrException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrException.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public FunctionParserTokenManager(SimpleCharStream stream){
    input_stream = stream;
  }

  /** Constructor. */
  public FunctionParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 83; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrException("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrException.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xff781L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[83];
    private final int[] jjstateSet = new int[2 * 83];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
