/* FunctionParser.java */
/* Generated by:  JJTree&ParserGeneratorCC: Do not edit this line. FunctionParser.java */
package com.github.vincentrussell.json.datagenerator.parser;

import com.github.vincentrussell.json.datagenerator.functions.FunctionRegistry;
import com.google.common.base.Charsets;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

/**
 * An Arithmetic Grammar.
 */
public class FunctionParser/*@bgen(jjtree)*/ implements FunctionParserTreeConstants, FunctionParserConstants {/*@bgen(jjtree)*/
    protected JJTFunctionParserState jjtree = new JJTFunctionParserState();
    private FunctionRegistry functionRegistry;

    public void setFunctionRegistry(final FunctionRegistry functionRegistry) {
        this.functionRegistry = functionRegistry;
    }

    /**
     * Main entry point.
     */
    public static void main(String args[]) {
        System.out.println("Reading from standard input...");
        FunctionParser t = new FunctionParser(System.in, Charsets.UTF_8);
        try {
            SimpleNode n = t.Start();
            n.dump("");
            System.out.println("Thank you.");
        } catch (Exception e) {
            System.out.println("Oops.");
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Main production.
     */
    final public SimpleNode Start() throws ParseException, InvocationTargetException, IllegalAccessException {/*@bgen(jjtree) Start */
        SimpleNode jjtn000 = new SimpleNode(JJTSTART);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        try {
            Function();
            jj_consume_token(0);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return jjtn000;
            }
        } catch (Throwable jjte000) {
            if (jjtc000) {
                jjtree.clearNodeScope(jjtn000);
                jjtc000 = false;
            } else {
                jjtree.popNode();
            }
            if (jjte000 instanceof ParseException) {
                throw (ParseException) jjte000;
            }
            if (jjte000 instanceof RuntimeException) {
                throw (RuntimeException) jjte000;
            }
            if (jjte000 instanceof InvocationTargetException) {
                throw (InvocationTargetException) jjte000;
            }
            if (jjte000 instanceof IllegalAccessException) {
                throw (IllegalAccessException) jjte000;
            }
            throw (Error) jjte000;
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public String FunctionName() throws ParseException {/*@bgen(jjtree) FunctionName */
        SimpleNode jjtn000 = new SimpleNode(JJTFUNCTIONNAME);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        Token t = null;
        try {
            t = jj_consume_token(IDENTIFIER);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return t.image;
            }
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public String DoubleQuotedStringLiteral() throws ParseException {/*@bgen(jjtree) DoubleQuotedStringLiteral */
        SimpleNode jjtn000 = new SimpleNode(JJTDOUBLEQUOTEDSTRINGLITERAL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        Token t = null;
        try {
            t = jj_consume_token(DOUBLE_QUOTED_STRING_LITERAL);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return t.image.replaceAll("^\"|\"$", "");
            }
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public String SingleQuotedStringLiteral() throws ParseException {/*@bgen(jjtree) SingleQuotedStringLiteral */
        SimpleNode jjtn000 = new SimpleNode(JJTSINGLEQUOTEDSTRINGLITERAL);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        Token t = null;
        try {
            t = jj_consume_token(SINGLE_QUOTED_STRING_LITERAL);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return t.image.replaceAll("^'|'$", "");
            }
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public String Number() throws ParseException {/*@bgen(jjtree) Number */
        SimpleNode jjtn000 = new SimpleNode(JJTNUMBER);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        Token t = null;
        try {
            t = jj_consume_token(NUMBER);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            final String value = t.image;
            jjtn000.jjtSetValue(value);
            {
                if ("" != null) return value;
            }
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public void Function() throws ParseException, InvocationTargetException, IllegalAccessException {/*@bgen(jjtree) Function */
        SimpleNode jjtn000 = new SimpleNode(JJTFUNCTION);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        try {
            FunctionName();
            FormalParameters();
        } catch (Throwable jjte000) {
            if (jjtc000) {
                jjtree.clearNodeScope(jjtn000);
                jjtc000 = false;
            } else {
                jjtree.popNode();
            }
            if (jjte000 instanceof ParseException) {
                throw (ParseException) jjte000;
            }
            if (jjte000 instanceof RuntimeException) {
                throw (RuntimeException) jjte000;
            }
            if (jjte000 instanceof InvocationTargetException) {
                throw (InvocationTargetException) jjte000;
            }
            if (jjte000 instanceof IllegalAccessException) {
                throw (IllegalAccessException) jjte000;
            }
            throw (Error) jjte000;
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
    }

    final public String Parse() throws ParseException, InvocationTargetException, IllegalAccessException {/*@bgen(jjtree) Parse */
        SimpleNode jjtn000 = new SimpleNode(JJTPARSE);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        String functionName = null;
        String[] parameters = null;
        try {
            functionName = FunctionName();
            parameters = FormalParameters();
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return executeRegisteredFunction(functionName, parameters);
            }
        } catch (Throwable jjte000) {
            if (jjtc000) {
                jjtree.clearNodeScope(jjtn000);
                jjtc000 = false;
            } else {
                jjtree.popNode();
            }
            if (jjte000 instanceof ParseException) {
                throw (ParseException) jjte000;
            }
            if (jjte000 instanceof RuntimeException) {
                throw (RuntimeException) jjte000;
            }
            if (jjte000 instanceof InvocationTargetException) {
                throw (InvocationTargetException) jjte000;
            }
            if (jjte000 instanceof IllegalAccessException) {
                throw (IllegalAccessException) jjte000;
            }
            throw (Error) jjte000;
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    /**
     * Execute a registered function in a clear, non-magic way.
     * Always pass the parameters array (may be empty). This avoids using null as a
     * sentinel "no-parameters" value.
     */
    private String executeRegisteredFunction(final String functionName, final String[] parameters)
            throws InvocationTargetException, IllegalAccessException {
        // FunctionRegistry.executeFunction accepts varargs. Passing an empty array is clearer than null.
        return functionRegistry.executeFunction(functionName, parameters);
    }

    final public String[] FormalParameters() throws ParseException, InvocationTargetException, IllegalAccessException {/*@bgen(jjtree) FormalParameters */
        SimpleNode jjtn000 = new SimpleNode(JJTFORMALPARAMETERS);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        String parameter;
        List<String> parameters = new ArrayList<String>();
        try {
            jj_consume_token(17);
            switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
                case DOUBLE_QUOTED_STRING_LITERAL:
                case SINGLE_QUOTED_STRING_LITERAL:
                case NUMBER:
                case IDENTIFIER: {
                    parameter = FormalParameter();
                    parameters.add(parameter);
                    label_1:
                    while (true) {
                        switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
                            case 18: {
                                break;
                            }
                            default:
                                jj_la1[0] = jj_gen;
                                break label_1;
                        }
                        jj_consume_token(18);
                        parameter = FormalParameter();
                        parameters.add(parameter);
                    }
                    break;
                }
                default:
                    jj_la1[1] = jj_gen;
                    ;
            }
            jj_consume_token(19);
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return parameters.toArray(new String[parameters.size()]);
            }
        } catch (Throwable jjte000) {
            if (jjtc000) {
                jjtree.clearNodeScope(jjtn000);
                jjtc000 = false;
            } else {
                jjtree.popNode();
            }
            if (jjte000 instanceof ParseException) {
                throw (ParseException) jjte000;
            }
            if (jjte000 instanceof RuntimeException) {
                throw (RuntimeException) jjte000;
            }
            if (jjte000 instanceof InvocationTargetException) {
                throw (InvocationTargetException) jjte000;
            }
            if (jjte000 instanceof IllegalAccessException) {
                throw (IllegalAccessException) jjte000;
            }
            throw (Error) jjte000;
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    final public String FormalParameter() throws ParseException, InvocationTargetException, IllegalAccessException {/*@bgen(jjtree) FormalParameter */
        SimpleNode jjtn000 = new SimpleNode(JJTFORMALPARAMETER);
        boolean jjtc000 = true;
        jjtree.openNodeScope(jjtn000);
        String t = null;
        try {
            switch (jj_ntk == -1 ? jj_ntk_f() : jj_ntk) {
                case DOUBLE_QUOTED_STRING_LITERAL: {
                    t = DoubleQuotedStringLiteral();
                    break;
                }
                case SINGLE_QUOTED_STRING_LITERAL: {
                    t = SingleQuotedStringLiteral();
                    break;
                }
                case NUMBER: {
                    t = Number();
                    break;
                }
                case IDENTIFIER: {
                    t = Parse();
                    break;
                }
                default:
                    jj_la1[2] = jj_gen;
                    jj_consume_token(-1);
                    throw new ParseException();
            }
            jjtree.closeNodeScope(jjtn000, true);
            jjtc000 = false;
            {
                if ("" != null) return t;
            }
        } catch (Throwable jjte000) {
            if (jjtc000) {
                jjtree.clearNodeScope(jjtn000);
                jjtc000 = false;
            } else {
                jjtree.popNode();
            }
            if (jjte000 instanceof ParseException) {
                throw (ParseException) jjte000;
            }
            if (jjte000 instanceof RuntimeException) {
                throw (RuntimeException) jjte000;
            }
            if (jjte000 instanceof InvocationTargetException) {
                throw (InvocationTargetException) jjte000;
            }
            if (jjte000 instanceof IllegalAccessException) {
                throw (IllegalAccessException) jjte000;
            }
            throw (Error) jjte000;
        } finally {
            if (jjtc000) {
                jjtree.closeNodeScope(jjtn000, true);
            }
        }
        throw new IllegalStateException("Missing return statement in function");
    }

    /**
     * Generated Token Manager.
     */
    public FunctionParserTokenManager token_source;
    SimpleCharStream jj_input_stream;
    /**
     * Current token.
     */
    public Token token;
    /**
     * Next token.
     */
    public Token jj_nt;
    private int jj_ntk;
    private int jj_gen;
    final private int[] jj_la1 = new int[3];
    static private int[] jj_la1_0;

    static {
        jj_la1_init_0();
    }

    private static void jj_la1_init_0() {
        jj_la1_0 = new int[]{0x40000, 0x4380, 0x4380,};
    }

    /**
     * Constructor with InputStream.
     *
     * @param stream input stream
     */
    public FunctionParser(final java.io.InputStream stream) {
        this(stream, null);
    }

    /**
     * Constructor with InputStream and supplied encoding
     *
     * @param stream   input stream
     * @param encoding charset to be used
     */
    public FunctionParser(final java.io.InputStream stream, final java.nio.charset.Charset encoding) {
        jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1);
        token_source = new FunctionParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++) jj_la1[i] = -1;
    }

    /**
     * Reinitialise
     *
     * @param stream input stream
     */
    public void ReInit(final java.io.InputStream stream) {
        ReInit(stream, null);
    }

    /**
     * Reinitialise
     *
     * @param stream   input stream
     * @param encoding charset to be used
     */
    public void ReInit(final java.io.InputStream stream, final java.nio.charset.Charset encoding) {
        jj_input_stream.reInit(stream, encoding, 1, 1);
        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++) jj_la1[i] = -1;
    }

    /**
     * Constructor with InputStream.
     *
     * @param stream char stream
     */
    public FunctionParser(final java.io.Reader stream) {
        jj_input_stream = new SimpleCharStream(stream, 1, 1);
        token_source = new FunctionParserTokenManager(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++)
            jj_la1[i] = -1;
    }

    /**
     * Reinitialise
     *
     * @param stream char stream
     */
    public void ReInit(final java.io.Reader stream) {
        if (jj_input_stream == null) {
            jj_input_stream = new SimpleCharStream(stream, 1, 1);
        } else {
            jj_input_stream.reInit(stream, 1, 1);
        }
        if (token_source == null) {
            token_source = new FunctionParserTokenManager(jj_input_stream);
        }

        token_source.ReInit(jj_input_stream);
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++)
            jj_la1[i] = -1;
    }

    /**
     * Constructor with generated Token Manager.
     *
     * @param tm Token manager to use
     */
    public FunctionParser(final FunctionParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++) jj_la1[i] = -1;
    }

    /**
     * Reinitialise
     *
     * @param tm Token manager to use
     */
    public void ReInit(final FunctionParserTokenManager tm) {
        token_source = tm;
        token = new Token();
        jj_ntk = -1;
        jj_gen = 0;
        for (int i = 0; i < 3; i++) jj_la1[i] = -1;
    }

    private Token jj_consume_token(final int kind) throws ParseException {
        final Token oldToken = token;
        if (token.next != null)
            token = token.next;
        else {
            token.next = token_source.getNextToken();
            token = token.next;
        }
        jj_ntk = -1;
        if (token.kind == kind) {
            jj_gen++;
            return token;
        }
        token = oldToken;
        jj_kind = kind;
        throw generateParseException();
    }


    /**
     * @return the next Token.
     */
    public final Token getNextToken() {
        if (token.next != null)
            token = token.next;
        else
            token = token.next = token_source.getNextToken();
        jj_ntk = -1;
        jj_gen++;
        return token;
    }

    /**
     * @param index index to be retrieved
     * @return the specific Token.
     */
    public final Token getToken(final int index) {
        Token t = token;
        for (int i = 0; i < index; i++) {
            if (t.next == null)
                t.next = token_source.getNextToken();
            t = t.next;
        }
        return t;
    }

    private int jj_ntk_f() {
        jj_nt = token.next;
        if (jj_nt == null) {
            token.next = token_source.getNextToken();
            jj_ntk = token.next.kind;
            return jj_ntk;
        }
        jj_ntk = jj_nt.kind;
        return jj_ntk;
    }

    private java.util.List<int[]> jj_expentries = new java.util.ArrayList<>();
    private int[] jj_expentry;
    private int jj_kind = -1;

    /**
     * Generate ParseException.
     *
     * @return new Exception object. Never <code>null</code>
     */
    public ParseException generateParseException() {
        jj_expentries.clear();
        boolean[] la1tokens = new boolean[20];
        if (jj_kind >= 0) {
            la1tokens[jj_kind] = true;
            jj_kind = -1;
        }
        for (int i = 0; i < 3; i++) {
            if (jj_la1[i] == jj_gen) {
                for (int j = 0; j < 32; j++) {
                    if ((jj_la1_0[i] & (1 << j)) != 0) {
                        la1tokens[j] = true;
                    }
                }
            }
        }
        for (int i = 0; i < 20; i++) {
            if (la1tokens[i]) {
                jj_expentry = new int[1];
                jj_expentry[0] = i;
                jj_expentries.add(jj_expentry);
            }
        }
        int[][] exptokseq = new int[jj_expentries.size()][];
        for (int i = 0; i < jj_expentries.size(); i++) {
            exptokseq[i] = jj_expentries.get(i);
        }
        return new ParseException(token, exptokseq, tokenImage);
    }

    /**
     * @return Always <code>false</code>.
     */
    public final boolean trace_enabled() {
        return false;
    }

    /**
     * Enable tracing.
     */
    public final void enable_tracing() {
    }

    /**
     * Disable tracing.
     */
    public final void disable_tracing() {
    }

}
