/* Generated by: ParserGeneratorCC: Do not edit this line. FunctionParserTreeConstants.java Version 1.1.3 */
package com.github.vincentrussell.json.datagenerator.parser;

public interface FunctionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCTIONNAME = 1;
  public int JJTDOUBLEQUOTEDSTRINGLITERAL = 2;
  public int JJTSINGLEQUOTEDSTRINGLITERAL = 3;
  public int JJTNUMBER = 4;
  public int JJTFUNCTION = 5;
  public int JJTPARSE = 6;
  public int JJTFORMALPARAMETERS = 7;
  public int JJTFORMALPARAMETER = 8;


  public String[] jjtNodeName = {
    "Start",
    "FunctionName",
    "DoubleQuotedStringLiteral",
    "SingleQuotedStringLiteral",
    "Number",
    "Function",
    "Parse",
    "FormalParameters",
    "FormalParameter",
  };
}
/* ParserGeneratorCC - OriginalChecksum=ad23e95a0b8d0b3d8e910ef0adb962f7 (do not edit this line) */
