package com.github.loadup.testify.model;
public enum AssertionType {
    EQUALS, NOT_EQUALS, NOT_NULL, NULL, CONTAINS, NOT_CONTAINS,
    STARTS_WITH, ENDS_WITH, GREATER_THAN, LESS_THAN,
    GREATER_THAN_OR_EQUALS, LESS_THAN_OR_EQUALS, IN_RANGE,
    MATCHES_REGEX, HAS_SIZE, IS_EMPTY, IS_NOT_EMPTY,
    INSTANCE_OF, COLLECTION_CONTAINS, COLLECTION_NOT_CONTAINS
}
