package com.github.loadup.testify.model;
public enum VerificationRule {
    EQUALS, NOT_EQUALS, NOT_NULL, NULL,
    GREATER_THAN, LESS_THAN, GREATER_THAN_OR_EQUALS, LESS_THAN_OR_EQUALS,
    CONTAINS, STARTS_WITH, ENDS_WITH, IN_LIST, NOT_IN_LIST,
    TIME_CLOSE_TO, DATE_EQUALS, REGEX_MATCH
}
